---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    app_context: kind-kind-cilium
    app_state: present
    namespace: db-testing
  tasks:
    - name: namespace
      kubernetes.core.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: "{{ app_state }}"
        context: "{{ app_context }}"

    - name: bitnami helm repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: postgresql helmchart
      kubernetes.core.helm:
        name: postgresql0
        chart_ref: bitnami/postgresql
        release_namespace: "{{ namespace }}"
        state: "{{app_state}}"
        values: {}

    - name: test connection
      kubernetes.core.k8s:
        state: "{{ app_state }}"
        namespace: "{{ namespace }}"
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            labels:
              run: sh
            name: sh
          spec:
            containers:
            - args:
              # - sh
              # - -c
              # - apk add bind-tools && dig postgres.ns.cluster.svc.local
              - sh
              image: alpine
              name: connection-tester
