---

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Add rancher chart repo
      kubernetes.core.helm_repository:
        name: rancher-stable
        repo_url: https://releases.rancher.com/server-charts/stable

    - name: Deploy latest version of rancher chart
      kubernetes.core.helm:
        state: present
        name: rancher
        atomic: true 
        chart_ref: rancher-stable/rancher
        release_namespace: cattle-system
        context: kind-kind-cilium
        create_namespace: true
        values:
          hostname: rancher.my.org
          ingress:
            enabled: false
          tls: external
          bootstrapPassword: "123"
      