- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: install truecharts repo
      kubernetes.core.helm_repository:
        name: truecharts
        repo_url: https://charts.truecharts.org

    - name: install pihole chart
      kubernetes.core.helm:
        name: pihole
        update_repo_cache: true
        chart_ref: truecharts/pihole
        create_namespace: true
        release_namespace: pihole
        wait: true
        values:
          pihole:
            WEBPASSWORD: "123"
            DNS1: 8.8.8.8
            DNS2: 1.1.1.1
